### ISSUE TITLE
Fix for #282 seems to have left the test broken

### ISSUE THREAD

**Issue by randombit** [C2SP/x509-limbo#292]
#287 removed the SAN entirely from the test certificate, but the test still expects/requires there to be a DNS name `'expected_peer_name': {'kind': 'DNS', 'value': 'example.com'}` so the chain is, AIUI, invalid.

**Comment by alex** [comment]
Line 494 has `expected_peer_name(None)`, you're saying it still has an expected name in the JSON?

**Comment by randombit** [comment]
I was looking at the wrong file, false alarm

**Comment by alex** [comment]
Glad to hear it :-)
