### ISSUE TITLE
Testcase model: allow setting maximum chain-building depth

### ISSUE THREAD

**Issue by woodruffw** [C2SP/x509-limbo#58]
Most X.509 validation APIs expose an API for setting a maximum-chain building depth, e.g. `X509_VERIFY_PARAM_set_depth` for OpenSSL. We should expose a similar setting in our testcase model and builder, to exercise these APIs.

NB: This depth normally refers to the maximum number of non-self-issued intermediate CA certificates that appear in the chain, i.e. is _generally_ 2 less than the actual maximal depth (which includes the end-entity and the trust anchor).

**Comment by woodruffw** [comment]
Specifically, this should probably be something like: `max_intermediate_depth: int | None` (where `None` indicates "do whatever the implementation does by default").

**Comment by woodruffw** [comment]
Looks like Go's `crypto/x509` doesn't support a configurable maximum path length, so this will probably need to be behind some kind of `Feature` variant.

**Comment by woodruffw** [comment]
To enumerate the cases here a bit:

* A depth of `0` means that the only possible valid chains are `TA -> leaf`, i.e. from a trust root member to the leaf (since neither is an intermediate, the intermediate chain length is `0`)
* A depth of `1` means `TA (-> CA')* -> leaf`, where `(-> CA')*` means "zero or more intermediate CA certificates from the same *logical* CA" (i.e., self-issued CA certs)
  * A counterexample for this case would be `TA -> CA' -> CA'' -> leaf`, since `CA'` and `CA''` are not the same logical CA

**Comment by tetsuo-cpp** [comment]
I believe we need to firstly expose this option in the pyca/crypto API since it currently defaults to setting it to 8. I'll work on that first and then come up with some testcases.
